### ISSUE TITLE
Server config nonfunctional

### ISSUE THREAD

**Issue by milkev** [STS15/Fargos-Talismans#3]
It would be cool if you could toggle certain abilities of the combined talismans live in-game, on a per player basis for multiplayer.

Im aware of the config options, which im thankful for in singleplayer, but in a multiplayer environment certain players may want certain effects while others dont and its impossible to satisfy all of them with only a server side config.

One idea could be to make it controlled by nbt-data/components on the item itself, then you dont have to mess with player data or anything. Could be useful even if theres no way to change it in survival, since you would be able to modify it per-player with /data.

edit: after toying with the config file, it doesnt seem like the effects are actually disabled, atleast not when using the final soul accessory. The config file also does not contain toggles for the souls

**Comment by STS15** [comment]
Hey, thanks for the suggestion.  I need to add some more documentation since there is actually a command to toggle the talismans (Not souls yet) in game.  You can manually toggle specific talismans using "/fargostalismans talisman toggle air_talisman" of if you're like me and more of a visual person, you can use the gui, also accessible from command "/fargostalismans talisman gui". This should all be on a per player basis. 

In regards to the server config not working, I'll have to do some more testing on that as that may be a bug.  I'm assuming 1.21 on 2.0.6

In the next update (within the week) I'll have the server side config fixed as well as adding the souls to be toggled.

**Comment by STS15** [comment]
Server Configs removed from mod for the time being while I am able to set them up properly with a network handler packet.  Did not make it into 2.0.8 release.
